### ISSUE TITLE
Record keeping structure 🐧

### ISSUE THREAD

**Issue by rwanyoike** [nairobilug/nairobilug.or.ke#102]
Our friends over at Ubuntu ZA (https://ubuntu-za.org/), have a neat record keeping structure on their website (https://wiki.ubuntu.com/ZATeam/TeamReports, https://wiki.ubuntu.com/ZATeam/Meetings)

What do you think of creating such a structure for the LUG, mainly for our meetups? 

We don't need anything complex. Someone can hack an interactive script or web app that generates a consistent doc (eg markdown) for the site.

**Comment by raymondwanyoike** [comment]
If we ever agree to regular IRC meetups, we can have a bot to record and create the same.

**Comment by alanorth** [comment]
I'm super not into IRC meetups; we can meet in person whenever we want! But we should definitely commit to writing blog posts for every meetup, and then archiving (although posting on the blog could be enough, or at least we could link to it in a real archive).

**Comment by raymondwanyoike** [comment]
There's one problem, getting getting people to commit. To make it *appear* less daunting?

**Comment by alanorth** [comment]
I know IRC meetups are used for groups where the users are distributed.
Like open source projects with developers in many countries.

**Comment by raymondwanyoike** [comment]
I was referring to meetup posts, committing to writing them.

**Comment by alanorth** [comment]
Sorry, broheim. Yep, we've been pretty lucky to have people help with
writing posts about the meetings... I think we should just continue to
encourage and support people to write posts, but maybe make it a more
formal process, like talk about it towards the end of the meetups and kinda
elect someone.

**Comment by rwanyoike** [comment]
> I think we should just continue to encourage and support people to write posts, but maybe make it a more formal process, like talk about it towards the end of the meetups and kinda elect someone.
