### ISSUE TITLE
Get rid of theme submodule?

### ISSUE THREAD

**Issue by alanorth** [nairobilug/nairobilug.or.ke#107]
It's pretty confusing for new users who try to get started after the initial checkout. Also, it complicates pull requests, like #95, which is opened on the blog repo, but mostly affects the theme repo. Sometimes even I forget to update the submodule on one or other of my dev machines, and only realize something is broken when I push the resulting gh-pages to github!

What do you think about this @raymondwanyoike? We could just move the theme into this repository under the "theme" path...?

**Comment by raymondwanyoike** [comment]
Good idea.

We can look into how to integrate the submodule without losing any history.

**Comment by alanorth** [comment]
I actually think we should keep the theme as a submodule so other people can use it easily. Lately there have been several pull requests and issues filed there, so people are actually using it!!! Cool :+1:
