### ISSUE TITLE
Do you have an idea for the blog?

### ISSUE THREAD

**Issue by rwanyoike** [nairobilug/nairobilug.or.ke#133]
Do you have an idea for the blog? It's great at tracking meetups, and exposing the LUG, but do you think it's representing the cool, and _dynamic_ elements that make Nairobi LUG? I think we can all agree LUG is unique :poultry_leg:, _hipsters_, scientists, artists, hackers, casuals etc; Why don't we represent that.

**Comment by raymondwanyoike** [comment]
Earlier ideas:

- Add a page for spin-off groups, #99
- Spice up our logo, #100

**Comment by oguya** [comment]
@raymondwanyoike what about adding Travis CI build for the nairobi.or.ke repo ?

**Comment by raymondwanyoike** [comment]
@oguya What are some of the tests that would have?

**Comment by alanorth** [comment]
He just wants to have a green "build passing" button. ;)

**Comment by rwanyoike** [comment]
Closing this. New idea's are always welcome. 🐝
