### ISSUE TITLE
TLS exception while fetching webpage http://nairobilug.or.ke

### ISSUE THREAD

**Issue by urbanslug** [nairobilug/nairobilug.or.ke#140]
This is happening when I try to access the page through the IRC bot. It could fail to be the fault a library I am depending on (simpleirc) but I think not because it only happens with  http://nairobilug.or.ke

`TlsExceptionHostPort (HandshakeFailed (Error_Protocol ("expecting server hello, got alert : [(AlertLevel_Fatal,HandshakeFailure)]",True,HandshakeFailure))) "nairobilug.or.ke" 443`

**Comment by alanorth** [comment]
I'm guessing your library supports old cryptographic ciphers. Try on
another website that is running Cloudflare's TLS, I bet it's the same.
