### ISSUE TITLE
Restore mailing list

### ISSUE THREAD

**Issue by fredmanglis** [nairobilug/nairobilug.or.ke#143]
Seems like someone deleted the nairobi-gnu@googlegroups.com mailing list. We need to restore that.

I'm on mobile and realise this might not be the best place, but I have to put this down somewhere before too much time is gone

**Comment by oguya** [comment]
All my mail responses have bounced back! This is so messed up!!

**Comment by poppingtonic** [comment]
Whoa, this is weird! Who created it? Why would someone want to obliterate this community's conversation history?

**Comment by jasonrogena** [comment]
LOL, we got pwned

**Comment by alanorth** [comment]
Oh god, first the IRC bouncer dies, then this?

Now someone should download and parse their mail client's IMAP folder and
post the archive online for posterity. :D

Alan

On Mon, Feb 8, 2016 at 3:15 PM Jason Rogena <notifications@github.com>
wrote:

> LOL, we got pwned
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nairobilug/nairobilug.or.ke/issues/143#issuecomment-181362131>
> .
>
-- 

Alan Orth
alan.orth@gmail.com
https://englishbulgaria.net
https://alaninkenya.org
https://mjanja.ch

**Comment by poppingtonic** [comment]
Here's 323 daily digests from my archives: https://drive.google.com/file/d/0B96FnYrZ4SRIRmc5R1dmR3hPa2c/view?usp=sharing

**Comment by fredmanglis** [comment]
Hey everyone. Before we all panic and burn a witch, can we get some idea
what happened. I admit I jumped to a hasty conclusion that it was deleted,
but could we get some feedback.

Who has admin access? Can said admin access mailing list? Could there have
been an issue with configuration/settings update?

**Comment by rwanyoike** [comment]
Hi, it was my fault. Sorry about this. It should be back now. I'm composing an email about what happened. :disappointed:

**Comment by oguya** [comment]
@rwanyoike 
Even better, a blog post: _How I 404'd NairobiLUG Mailing List_ 
:wink:

**Comment by urbanslug** [comment]
This is hilarious hahahaha
