### ISSUE TITLE
Use new pelican Makefile.

### ISSUE THREAD

**Issue by urbanslug** [nairobilug/nairobilug.or.ke#148]
Can we use the modern "version" of pelican and get nicities such as make devserver that make the development process smoother? Example see: https://github.com/urbanslug/urbanslug.github.io even though I don't use it.

@alanorth @rwanyoike @oguya  @jasonrogena Is there a reason we are using what we are using and shouldn't "upgrade"?

I could get this done if I have your go ahead.

**Comment by rwanyoike** [comment]
Give it a shot!
