### ISSUE TITLE
Migrate to nairobi.lug.or.ke

### ISSUE THREAD

**Issue by bkmgit** [nairobilug/nairobilug.or.ke#204]

**Comment by BonfaceKilz** [comment]
Seems you fixed this.  So I'll go ahead and merge
this.  I also see that https://nairobi.lug.or.ke.
Perhaps create a new thread for this?  I can do
that myself later tonight.

-- 
(Life is like a pencil that will surely run out,
    but will leave the beautiful writing of life.)
(D4F09EB110177E03C28E2FE1F5BBAE1E0392253F
    (hkp://keys.openpgp.org))

**Comment by BonfaceKilz** [comment]
Regardless.  Thanks for creating the time and
space to work on this!

-- 
(Life is like a pencil that will surely run out,
    but will leave the beautiful writing of life.)
(D4F09EB110177E03C28E2FE1F5BBAE1E0392253F
    (hkp://keys.openpgp.org))
