### ISSUE TITLE
Update Pelican to 3.5.0

### ISSUE THREAD

**Issue by alanorth** [nairobilug/nairobilug.or.ke#87]
I just checked and there is a [new release of Pelican](http://docs.getpelican.com/en/latest/changelog.html#id1) since a few weeks ago.  All we have to do is make sure the local Pelican is updated in the virtualenv the next time we generate the HTML.  //cc @raymondwanyoike 

On a related note, we should be remembering to update our environments from time to time...

```console
$ pip list --outdated
Markdown (Current: 2.5.1 Latest: 2.5.2)
pelican (Current: 3.4.0 Latest: 3.5.0)
python-dateutil (Current: 2.2 Latest: 2.3)
pytz (Current: 2014.7 Latest: 2014.10)
Pygments (Current: 1.6 Latest: 2.0.1)
$ pip freeze --local | grep -v '^\-e' | cut -d = -f 1  | xargs pip install -U
```

**Comment by rwanyoike** [comment]
Noted.

https://github.com/nairobilug/nairobilug.or.ke/blob/18675e9/requirements.txt#L3
