### ISSUE TITLE
Add sitemap.xml

### ISSUE THREAD

**Issue by alanorth** [nairobilug/nairobilug.or.ke#93]
We need this so we can have search bots index our content better (as opposed to just stumbling upon us and scraping HTML).  See here for Pelican-specific notes on generating a `sitemap.xml`:

https://github.com/getpelican/pelican/wiki/Tips-n-Tricks

Perhaps @urbanslug or @jasonrogena could do it to it...

**Comment by kenju254** [comment]
@alanorth I just found out that there is a plugin already in existence to generate sitemaps. https://github.com/getpelican/pelican-plugins/tree/master/sitemap

**Comment by raymondwanyoike** [comment]
I had started on it a while back, https://github.com/raymondwanyoike/pelican-alchemy/commit/3805b79 - something to work with? @urbanslug, @jasonrogena, @kenju254

**Comment by raymondwanyoike** [comment]
Wait, the plugin @kenju254 linked looks simpler.

**Comment by kenju254** [comment]
@raymondwanyoike  this is so much easier to implement and I will send some more details thanks to my other Pelican friend who did some hacks on it..

**Comment by alanorth** [comment]
I just added https://nairobilug.or.ke to the Nairobi LUG's Google Webmaster Tools in preparation. Once we create the sitemap @raymondwanyoike or I can add it there.

**Comment by alanorth** [comment]
Woop! Sitemap added to Google Webmaster Tools. Now Google can consume our content, rather than just kinda stumbling upon it and parsing it for links to index.

![screen shot 2015-02-06 at 23 46 22](https://cloud.githubusercontent.com/assets/191754/6087263/74e95058-ae5a-11e4-92ee-727b73b86301.png)
