### ISSUE TITLE
Enable Mandatory HTTPS

### ISSUE THREAD

**Issue by alanorth** [nairobilug/nairobilug.or.ke#96]
I've turned on CloudFlare's Universal HTTPS on the blog... as of commit 46ee51632ad503fb0cb991d0c7d699db814076d4, *all* requests are served over TLS + SPDY 3.1. Winning?

```console
$ http --headers http://nairobilug.or.ke
HTTP/1.1 301 Moved Permanently
CF-RAY: 1b47182708ad1467-AMS
Cache-Control: private, max-age=0, no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Connection: keep-alive
Date: Fri, 06 Feb 2015 11:44:11 GMT
Expires: Thu, 01 Jan 1970 00:00:01 GMT
Location: https://nairobilug.or.ke/
Server: cloudflare-nginx
Set-Cookie: __cfduid=d623d907e70023713ee5937d9156b0aea1423223051; expires=Sat, 06-Feb-16 11:44:11 GMT; path=/; domain=.nairobilug.or.ke; HttpOnly
Transfer-Encoding: chunked
```

![lug-https](https://cloud.githubusercontent.com/assets/191754/6078842/ac51d48a-ae0e-11e4-9105-92da735be0b0.png)

Generally, I followed this blog post: https://www.benburwell.com/posts/configuring-cloudflare-universal-ssl/

Note: I had to set pelican's siteurl to the HTTPS one so it writes links correctly; otherwise when you access the site with HTTPS the js, css, etc assets are fetched over HTTP which throws mixed-content errors in modern browsers.

**Comment by raymondwanyoike** [comment]
![carl-sagan-youre-awesome](https://cloud.githubusercontent.com/assets/3677497/6079732/2b200d12-ae1a-11e4-9f52-5f9d4ddd004e.gif)

**Comment by JohnTroony** [comment]
Great!
