### ISSUE TITLE
Add a page for spin-off groups

### ISSUE THREAD

**Issue by rwanyoike** [nairobilug/nairobilug.or.ke#99]
The LUG has a few spin-off groups formed by some members, e.g. [book club](https://www.goodreads.com/group/show/114053-nairobi-gnu-linux-users-group), traveling, 3D etc.

We should add a page that lists and promotes le groups.

**Comment by alanorth** [comment]
Good idea. "Affiliated organizations"?

**Comment by raymondwanyoike** [comment]
Yeah, like the sound of that.

**Comment by rwanyoike** [comment]
Great while it lasted. 🍻 This can still be done for any future ideas that gain traction.
